apiVersion: apps/v1
kind: Deployment
metadata:
  name: mewie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mewie
  template:
    metadata:
      labels:
        app: mewie
    spec:
      containers:
      - image: okteto.dev/mewie:latest
        name: mewie
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/L-html.zip"
        - name: Vless_UUID
          value: "b4941d3e-9f68-479c-ab24-9c9a238f5715"
        - name: Vless_Path
          value: "/9fb5794e-535c-4282-8b75-e593e20e264f-vless"
        - name: Vmess_UUID
          value: "b4941d3e-9f68-479c-ab24-9c9a238f5715"
        - name: Vmess_Path
          value: "/9fb5794e-535c-4282-8b75-e593e20e264f-vmess"
        - name: Share_Path
          value: "/rweenk"
